# Example: CNI host-device

cat <<EOF | kubectl create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: enp0s9-host-device-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "host-device",
      "device": "enp0s9"
    }'
EOF

---

cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: cni-host-pod
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: default/enp0s9-host-device-conf
spec:
  containers:
  - image: dougbtv/centos-network
    command:
    - sleep
    - "3600"
    imagePullPolicy: IfNotPresent
    name: dogtv
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
  restartPolicy: Never
EOF

# inside pod (script)
# ip addr add 40.40.40.101/24 dev net1
# ip link set net1 up
# ip route del default via 169.254.1.1
# ip route add default via 40.40.40.1
# ip route add Calico_CIDR via eth0

# Alternatively, source routing
# ip addr add 40.40.40.101/24 dev net1
# ip link set net1 up
# echo 200 custom >> /etc/iproute2/rt_tables
# ip rule add from 40.40.40.101/24 lookup custom
# ip route add default via 40.40.40.1 dev net1 table custom

# ip addr add 40.40.40.101/24 dev net1
# ip link set net1 up
# ip rule add from 40.40.40.101/24 table 200
# ip route add default via 40.40.40.1 dev net1 table 200

# ping -I 40.40.40.101 8.8.8.8


