# Example: CNI host-device
# kubectl label nodes w1 key=vm-w1

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: enp0s9-host-device-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "host-device",
      "device": "enp0s9"
    }'

---

apiVersion: v1
kind: Pod
metadata:
  name: dogtv
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: default/enp0s9-host-device-conf
spec:
  containers:
  - image: dougbtv/centos-network
    command:
    - sleep
    - "3600"
    imagePullPolicy: IfNotPresent
    name: dogtv
    securityContext:
      privileged: true
  nodeSelector:
    key: "vm-w1"
  restartPolicy: Never

# inside pod
# ip addr add 20.20.20.101/24 dev net1
# ip link set net1 up
# ip route del default via 10.244.1.1
# ip route add default via 20.20.20.1
