apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ens4-host-device-conf
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "host-device",
      "device": "ens4"
    }'
    
---

apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: default/ens4-host-device-conf
spec:
  containers:
  - image: busybox
    command:
    - sleep
    - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  nodeSelector:
    eegress: "1"
  restartPolicy: Never
  
  
