cat <<EOF | kubectl create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: ipvlan-conf-1
spec:
  config: '{
            "cniVersion": "0.3.1",
            "type": "ipvlan",
            "master": "enp0s9",
            "ipam": {
                "type": "host-local",
                "ranges": [
                    [ {
                         "subnet": "30.30.30.0/24",
                         "rangeStart": "30.30.30.20",
                         "rangeEnd": "30.30.30.50",
                         "gateway": "30.30.30.1"
                    } ]
                ]
            }
        }'
EOF

cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: samplepod1
  annotations:
    k8s.v1.cni.cncf.io/networks: ipvlan-conf-1
spec:
  containers:
  - name: samplepod1
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
EOF
