cat <<EOF | kubectl create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf-static
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "enp0s10",
      "mode": "bridge",
      "ipam": {
        "type": "static"
      }
    }'
EOF

---

cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: samplepod-macvlan
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "macvlan-conf-static", "ips": "40.40.40.101/24"}]'
spec:
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
EOF

---

# Nedded on Virtualbox
ip link set enp0s10 promisc on
# Source Routing
ip rule add from 40.40.40.101/24 table 200
ip route add default via 40.40.40.1 dev net1 table 200
# Firewall
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -A INPUT -j DROP
# Test
ping -I 40.40.40.101 8.8.8.8
ssh -b 40.40.40.101 test@a.b.c.d

# For host connectivity
# ip link add mynet-shim link enp0s10 type macvlan mode bridge
# ip addr add 40.40.40.50/32 dev mynet-shim
# ip link set mynet-shim up

