cat <<EOF | kubectl create -f -
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf-static
spec:
  config: '{
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "enp0s10",
      "mode": "bridge",
      "ipam": {
        "type": "static"
      }
    }'
EOF

---

cat <<EOF | kubectl create -f -
apiVersion: v1
kind: Pod
metadata:
  name: samplepod-macvlan
  annotations:
    k8s.v1.cni.cncf.io/networks: '[{ "name": "macvlan-conf-static", "ips": "40.40.40.101/24"}]'
spec:
  containers:
  - name: samplepod
    command: ["/bin/bash", "-c", "sleep 2000000000000"]
    image: dougbtv/centos-network
    securityContext:
      capabilities:
        add: ["NET_ADMIN"]
EOF

---

# Nedded on Virtualbox
ip link set enp0s10 promisc on
# Source Routing
ip rule add from 40.40.40.101/24 table 200
ip route add default via 40.40.40.1 dev net1 table 200
# Firewall
iptables -A INPUT -p tcp --dport 80 -j ACCEPT
iptables -A INPUT -j DROP
# Test
ping -I 40.40.40.101 8.8.8.8
ssh -b 40.40.40.101 test@a.b.c.d

# For host connectivity
# ip link add mynet-shim link enp0s10 type macvlan mode bridge
# ip addr add 40.40.40.50/24 dev mynet-shim
## ip route add 40.40.40.0/24 via dev mynet-shim
## ip route add 40.40.40.101/32 via 40.40.40.50
# ip link set mynet-shim up

root@W1:~# ip route
default via 40.40.40.1 dev enp0s10
10.10.10.0/24 dev enp0s3 proto kernel scope link src 10.10.10.101
blackhole 10.244.190.64/26 proto bird
10.244.190.92 dev cali307ad6411c8 scope link
20.20.20.0/24 dev enp0s8 proto kernel scope link src 20.20.20.101
30.30.30.0/24 dev enp0s9 proto kernel scope link src 30.30.30.101
40.40.40.0/24 dev enp0s10 proto kernel scope link src 40.40.40.40
40.40.40.101 via 40.40.40.50 dev mynet-shim
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown
root@W1:~#

[root@samplepod-macvlan /]# ip route
default via 169.254.1.1 dev eth0
40.40.40.0/24 dev net1  proto kernel  scope link  src 40.40.40.101
169.254.1.1 dev eth0  scope link
[root@samplepod-macvlan /]#



