apiVersion: v1
kind: Service
metadata:
  name: ubuntu-service
spec:
  selector:
    app: ubuntu-instance
  ports:
  - protocol: TCP
    port: 8022
  type: NodePort
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: ubuntu-deployment
spec:
  selector:
    matchLabels:
      app: ubuntu-instance
  replicas: 1 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: ubuntu-instance
    spec:
      containers:
      - name: ubuntu-container
        image: rastasheep/ubuntu-sshd
        command:
          - /usr/sbin/sshd 
          - "-D"
          - "-p"
          - "8022"                    
        ports:
        - containerPort: 8022
