apiVersion: v1
kind: Pod
metadata:
  name: sec-4
spec:
  containers:
  - name: sec-ctx-4
    image: ubuntu:18.04
    command:
      - /bin/bash
      - "-c"
      - "sleep 60m"
    securityContext:
      privileged: true
